// Generated by CoffeeScript 1.10.0
(function() {
  lib.assert = function() {
    return console.assert.apply(console, arguments);
  };

  lib.log = function() {
    return console.log.apply(console, arguments);
  };

  Math.clamp = function(v, a, b) {
    if (a <= b) {
      if (v < a) {
        return a;
      } else if (v > b) {
        return b;
      } else {
        return v;
      }
    } else {
      if (v < b) {
        return b;
      } else if (v > a) {
        return a;
      } else {
        return v;
      }
    }
  };

  Math.lerp = function(a, b, p) {
    p = Math.clamp(p, 0, 1);
    if (a <= b) {
      return a + (b - a) * p;
    } else {
      return b + (a - b) * (1 - p);
    }
  };

}).call(this);

//# sourceMappingURL=functions.js.map
