// Generated by CoffeeScript 1.10.0
(function() {
  lib.assert = function() {
    return console.assert.apply(console, arguments);
  };

  lib.log = function() {
    return console.log.apply(console, arguments);
  };

}).call(this);

//# sourceMappingURL=functions.js.map
