// Generated by CoffeeScript 1.10.0
(function() {
  var EntryScene,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EntryScene = (function(superClass) {
    extend(EntryScene, superClass);

    function EntryScene() {
      var bunny, texture;
      EntryScene.__super__.constructor.apply(this, arguments);
      texture = PIXI.Texture.fromImage('res/bunny.png');
      bunny = new PIXI.Sprite(texture);
      bunny.anchor.x = 0.5;
      bunny.anchor.y = 0.5;
      bunny.position.x = 200;
      bunny.position.y = 150;
      this.addChildRenderer(bunny);
      this._bunny = bunny;
    }

    EntryScene.prototype.update = function(dt) {
      EntryScene.__super__.update.apply(this, arguments);
      return this._bunny.rotation += 0.1;
    };

    return EntryScene;

  })(utils.SceneBase);

  (typeof exports !== "undefined" && exports !== null ? exports : this).EntryScene = EntryScene;

}).call(this);

//# sourceMappingURL=entry_scene.js.map
