// Generated by CoffeeScript 1.10.0
(function() {
  var M;

  M = {
    registerKey: function(keyCode) {
      var key;
      key = {
        code: keyCode,
        isDown: false,
        isUp: true,
        press: void 0,
        release: void 0,
        downHandler: function(event) {
          if (event.keyCode === key.code) {
            if (key.isUp && key.press) {
              key.press();
            }
            key.isDown = true;
            key.isUp = false;
          }
          return event.preventDefault();
        },
        upHandler: function(event) {
          if (event.keyCode === key.code) {
            if (key.isDown && key.release) {
              key.release();
            }
            key.isDown = false;
            key.isUp = true;
          }
          return event.preventDefault();
        }
      };
      window.addEventListener("keydown", key.downHandler.bind(key), false);
      window.addEventListener("keyup", key.upHandler.bind(key), false);
      return key;
    }
  };

  utils.InputManager = M;

}).call(this);

//# sourceMappingURL=input_manager.js.map
