// Generated by CoffeeScript 1.10.0
(function() {
  var SceneBase;

  SceneBase = (function() {
    function SceneBase() {
      this._renderer = new PIXI.Container();
    }

    SceneBase.prototype.destroy = function() {
      return this._renderer = null;
    };

    SceneBase.prototype.update = function(dt) {};

    SceneBase.prototype.getRenderer = function() {
      return this._renderer;
    };

    SceneBase.prototype.addChildRenderer = function(child_renderer) {
      this._renderer.addChild(child_renderer);
      return this;
    };

    SceneBase.prototype.addChild = function(child) {
      var child_renderer;
      child_renderer = child.getRenderer();
      this.addChildRenderer(child_renderer);
      return this;
    };

    return SceneBase;

  })();

  utils.SceneBase = SceneBase;

}).call(this);

//# sourceMappingURL=scene_base.js.map
