// Generated by CoffeeScript 1.10.0
(function() {
  var global;

  global = typeof exports !== "undefined" && exports !== null ? exports : this;

  global.lib = {};

  global.utils = {};

  global.components = {};

  global.resources = {};

}).call(this);

//# sourceMappingURL=init.js.map
